"""Optional OpenAI TTS. Never log text that may contain candidate PII by default."""

from __future__ import annotations

import hashlib
import os
from pathlib import Path

from zume.audio.base import SpeechProvider, SpeechResult
from zume.audio.browser import BrowserSpeechProvider


class OpenAITTSProvider(SpeechProvider):
    name = "openai_tts"

    def __init__(self, api_key: str, model: str | None = None, voice: str | None = None) -> None:
        self._api_key = api_key
        self._model = model or os.environ.get("OPENAI_TTS_MODEL", "gpt-4o-mini-tts")
        self._voice = voice or os.environ.get("OPENAI_TTS_VOICE", "alloy")
        self._cache = Path("data") / "audio-cache"
        self._fallback = BrowserSpeechProvider()

    def available(self) -> bool:
        return bool(self._api_key)

    def synthesize(self, text: str, *, voice: str | None = None, speed: float = 1.0) -> SpeechResult:
        del speed
        # Default policy: refuse empty text; callers must strip candidate PII.
        if not text.strip():
            return self._fallback.synthesize(text)
        voice = voice or self._voice
        digest = hashlib.sha256(f"{self._model}:{voice}:{text}".encode("utf-8")).hexdigest()[:32]
        self._cache.mkdir(parents=True, exist_ok=True)
        cache_path = self._cache / f"{digest}.mp3"
        if cache_path.exists():
            return SpeechResult(
                audio_bytes=cache_path.read_bytes(),
                mime_type="audio/mpeg",
                provider=self.name,
                ai_generated=True,
                disclosure="This audio is AI-generated by an optional OpenAI speech provider.",
                cache_path=str(cache_path),
            )
        # Live call is optional; degrade to browser descriptor when network unavailable.
        try:
            import json
            from urllib import request

            body = json.dumps(
                {"model": self._model, "voice": voice, "input": text, "format": "mp3"}
            ).encode("utf-8")
            req = request.Request(
                "https://api.openai.com/v1/audio/speech",
                data=body,
                headers={
                    "Authorization": f"Bearer {self._api_key}",
                    "Content-Type": "application/json",
                },
                method="POST",
            )
            with request.urlopen(req, timeout=45) as resp:
                audio = resp.read()
            cache_path.write_bytes(audio)
            return SpeechResult(
                audio_bytes=audio,
                mime_type="audio/mpeg",
                provider=self.name,
                ai_generated=True,
                disclosure="This audio is AI-generated by an optional OpenAI speech provider.",
                cache_path=str(cache_path),
            )
        except Exception:  # noqa: BLE001
            return self._fallback.synthesize(text)
