statuses:
  - RECEIVED
  - SCREENING
  - CONDITIONAL_SCREEN
  - DO_NOT_PROCEED
  - INTERVIEW_SCHEDULED
  - NO_SHOW
  - INTERVIEWED
  - SECOND_ROUND
  - SELECTED
  - REJECTED
  - ONBOARDING
  - HIRED
  - ARCHIVED
